# Generated by Django 3.2.5 on 2021-07-18 20:34

from django.db import migrations, models
import django.db.models.deletion
import django_model_snapshot_diff.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(blank=True, null=True)),
                ('text', models.CharField(max_length=255)),
                ('boolean', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_model_snapshot_diff.mixins.SnapshotMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ManyToMany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
            bases=(django_model_snapshot_diff.mixins.SnapshotMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[(1, 'A'), (2, 'B')], default=1, max_length=2)),
                ('rel_to_example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_to_example', to='example.example')),
            ],
            bases=(django_model_snapshot_diff.mixins.SnapshotMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ForeignKeyDeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('many_to_many', models.ManyToManyField(to='example.ManyToMany')),
            ],
            bases=(django_model_snapshot_diff.mixins.SnapshotMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ForeignKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('foreign_key_deeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.foreignkeydeeper')),
            ],
            bases=(django_model_snapshot_diff.mixins.SnapshotMixin, models.Model),
        ),
        migrations.AddField(
            model_name='example',
            name='foreign_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.foreignkey'),
        ),
    ]
